name: input_file_chunk_0
site:
  data:
    lat: -33.5265
    lon: 149.1588
    year: 2022
    site_boundaries:
      verts:
      - - 3.06
        - 288.87
      - - 0.0
        - 1084.03
      - - 1784.05
        - 1084.24
      - - 1794.09
        - 999.64
      - - 1494.34
        - 950.97
      - - 712.64
        - 262.8
      - - 1216.98
        - 272.36
      - - 1217.76
        - 151.62
      - - 708.14
        - 0.0
  desired_schedule: ../load_data/Load data.csv
  solar_resource_file: /mnt/c/Users/Hanrong Huang/OneDrive - UNSW/Desktop/py_microgrid/py_microgrid/simulation/resource_files/solar/-33.5265_149.1588_psmv3_60_2022.csv
  wind_resource_file: /mnt/c/Users/Hanrong Huang/OneDrive - UNSW/Desktop/py_microgrid/py_microgrid/simulation/resource_files/wind/-33.5265_149.1588_NASA_2022_60min_50m.srw
  hub_height: 50.0
  solar: true
  wind: true
  wave: false
financial:
  project_lifetime: 25
  discount_rate: 5.88
technologies:
  pv:
    system_capacity_kw: 9500.0
    config_file: ../../simulation/config/pv_config.yaml
  wind:
    num_turbines: 6
    turbine_rating_kw: 1000
    config_file: ../../simulation/config/wind_config.yaml
  battery:
    chemistry: LFPGraphite
    system_capacity_kw: 1900.0
    system_capacity_kwh: 8000.0
    config_file: ../../simulation/config/battery_config.yaml
  genset:
    interconnect_kw: 18300.0
    config_file: ../../simulation/config/genset_config.yaml
  grid:
    enabled: true
    interconnect_kw: 10000
    config_file: ../../simulation/config/grid_config.yaml
config:
  dispatch_config_file: ../../simulation/config/dispatch_config.yaml
  dispatch_options:
    battery_dispatch: predictive_demand_response
    grid_charging: true
    include_lifecycle_count: false
    n_look_ahead_periods: 48
    pv_charging_only: false
    solver: glpk
  simulation_options:
    start_year: 2022
    end_year: 2022
    time_steps_per_hour: 1
  optimization_options:
    algorithm: nelder_mead
    max_iterations: 1000
    tolerance: 1e-6
