name: quick_start_example
site:
  data:
    lat: -33.5265
    lon: 149.1588
    year: 2021
  desired_schedule: ./examples/parallel_simulations/load_data/Load data.csv
  solar_resource_file: /mnt/c/Users/Hanrong Huang/OneDrive - UNSW/Desktop/py_microgrid/py_microgrid/simulation/resource_files/solar/-33.5265_149.1588_psmv3_60_2020.csv
  wind_resource_file: /mnt/c/Users/Hanrong Huang/OneDrive - UNSW/Desktop/py_microgrid/py_microgrid/simulation/resource_files/wind/-33.5265_149.1588_NASA_2020_60min_50m.srw
financial:
  project_lifetime: 25
  discount_rate: 5.88
technologies:
  pv:
    system_capacity_kw: 29310.0
    config_file: ./py_microgrid/simulation/config/pv_config.yaml
  wind:
    num_turbines: 8
    turbine_rating_kw: 1000
    config_file: ./py_microgrid/simulation/config/wind_config.yaml
  battery:
    chemistry: LFPGraphite
    system_capacity_kw: 2931.0
    system_capacity_kwh: 5000.0
    config_file: ./py_microgrid/simulation/config/battery_config.yaml
  genset:
    interconnect_kw: 17000.0
    config_file: ./py_microgrid/simulation/config/genset_config.yaml
  grid:
    enabled: false
    interconnect_kw: 10000
    config_file: ./py_microgrid/simulation/config/grid_config.yaml
config:
  dispatch_config_file: ./py_microgrid/simulation/config/dispatch_config.yaml
  dispatch_options:
    battery_dispatch: predictive_demand_response
    grid_charging: false
    include_lifecycle_count: false
    n_look_ahead_periods: 48
    pv_charging_only: false
    solver: glpk
  simulation_options:
    start_year: 2020
    end_year: 2020
    time_steps_per_hour: 1
  optimization_options:
    max_iterations: 1000
    tolerance: 1e-6
    algorithm: nelder_mead
